// Lista filmów
export const movies = [
    {
      id: "1",
      title: "Casablanca",
      genre: "Drama/Romance",
      duration: "102 min",
      description: "II wojna światowa, Casablanca. Właściciel nocnego klubu, Rick Blaine, spotyka swoją dawną miłość, Ilsę, która okazuje się być żoną działacza czeskiego ruchu oporu, Victora Laszlo. Dawne uczucia odżywają.",
      showtimes: ["12:00", "14:30", "18:00"],
      image: "https://fwcdn.pl/fpo/09/05/905/7289268_1.10.webp",
    },
    {
      id: "2",
      title: "Ojciec chrzestny",
      genre: "Crime/Drama",
      duration: "175 min",
      description: "Opowieść o nowojorskiej rodzinie mafijnej. Starzejący się Don Corleone pragnie przekazać władzę swojemu synowi.",
      showtimes: ["11:00", "15:30", "19:00"],
      image: "https://fwcdn.pl/fpo/10/89/1089/7196615_1.10.webp",
    },
    {
      id: "3",
      title: "Pulp Fiction",
      genre: "Crime/Thriller",
      duration: "154 min",
      description: "Przemoc i odkupienie w opowieści o dwóch płatnych mordercach pracujących na zlecenie mafii, żonie gangstera, bokserze i parze okradającej ludzi w restauracji.",
      showtimes: ["17:30", "19:00", "21:00"],
      image: "https://fwcdn.pl/fpo/10/39/1039/7517880_1.10.webp",
    },
    {
      id: "4",
      title: "Forrest Gump",
      genre: "Drama/Romance",
      duration: "142 min",
      description: "Prosta historia Forresta Gumpa, który staje się świadkiem i uczestnikiem najważniejszych wydarzeń w historii USA.",
      showtimes: ["10:00", "13:30", "17:00"],
      image: "https://fwcdn.pl/fpo/09/98/998/8021615_1.10.webp",
    },
    {
      id: "5",
      title: "Fight Club",
      genre: "Drama",
      duration: "139 min",
      description: "Niezwykła relacja dwóch mężczyzn prowadzi do powstania klubu walki. Film o destrukcji i buncie przeciwko konsumpcyjnemu stylowi życia.",
      showtimes: ["16:00", "19:00", "21:30"],
      image: "https://fwcdn.pl/fpo/08/37/837/7522091_1.10.webp",
    },
    {
      id: "6",
      title: "Skazani na Shawshank",
      genre: "Drama",
      duration: "142 min",
      description: "Niesłusznie skazany na dożywocie bankier, Andy Dufresne, zaprzyjaźnia się z więźniem Redem i zdobywa szacunek w Shawshank.",
      showtimes: ["13:00", "16:30", "20:00"],
      image: "https://fwcdn.pl/fpo/10/48/1048/6925401_1.10.webp",
    },
    {
      id: "7",
      title: "Lśnienie",
      genre: "Horror",
      duration: "146 min",
      description: "Jack Torrance przyjmuje posadę stróża zimowego w odizolowanym hotelu. Wkrótce zaczyna popadać w obłęd.",
      showtimes: ["18:00", "20:30", "23:00"],
      image: "https://fwcdn.pl/fpo/10/20/1020/7183753_1.10.webp",
    },
    {
      id: "8",
      title: "Gwiezdne wojny: Nowa nadzieja",
      genre: "Sci-Fi/Adventure",
      duration: "121 min",
      description: "Luke Skywalker dołącza do rebeliantów, by pokonać Imperium i uwolnić galaktykę od tyranii.",
      showtimes: ["10:30", "14:00", "18:00"],
      image: "https://fwcdn.pl/fpo/07/59/759/8037811_1.10.webp",
    },
    {
      id: "9",
      title: "Indiana Jones: Poszukiwacze zaginionej Arki",
      genre: "Adventure",
      duration: "115 min",
      description: "Archeolog Indiana Jones wyrusza w pełną przygód podróż, by odnaleźć zaginioną Arkę Przymierza.",
      showtimes: ["12:00", "15:30", "19:00"],
      image: "https://fwcdn.pl/fpo/12/16/1216/7211116_1.7.webp",
    },
    {
      id: "10",
      title: "Matrix",
      genre: "Sci-Fi",
      duration: "136 min",
      description: "Haker Neo odkrywa, że świat, w którym żyje, jest symulacją stworzoną przez maszyny, i dołącza do walki o wolność ludzkości.",
      showtimes: ["14:00", "17:30", "21:00"],
      image: "https://fwcdn.pl/fpo/06/28/628/7685907_1.10.webp",
    },
    {
      id: "11",
      title: "Leon zawodowiec",
      genre: "Crime/Drama",
      duration: "110 min",
      description: "Zamachowiec Leon opiekuje się małą dziewczynką, której rodzina została zamordowana przez skorumpowanego policjanta.",
      showtimes: ["12:00", "16:30", "20:00"],
      image: "https://fwcdn.pl/fpo/06/71/671/8021401_1.10.webp",
    },
    {
      id: "12",
      title: "Powrót do przyszłości",
      genre: "Sci-Fi/Adventure",
      duration: "116 min",
      description: "Nastolatek Marty McFly przypadkowo przenosi się w czasie do lat 50., gdzie spotyka swoich rodziców.",
      showtimes: ["11:00", "14:30", "18:00"],
      image: "https://fwcdn.pl/fpo/88/23/8823/7862830_1.10.webp",
    },
  ];